### ISSUE TITLE
Type detection for string vs Svelte component?

### ISSUE THREAD

**Issue by jasongitmail** [etherCorps/sveltekit-og#16]
Thinking how to make the user experience as simple as possible for people, proposing an idea:

Would it be possible to use type detection to determine if the user passed a string or a Svelte Component? 

Then instead of exporting both `ImageResponse` and `componentToImageResponse`, you could export just one class or method, making usage simpler for devs.

Thoughts?

**Comment by theetherGit** [comment]
On this my pov was if we are providing component we also need it's props and this going to add some validation in our `ImageResponse` which is simple to use but if we change it for like to have component to people will get confuse especially bignners. Anf if i'm not wrong code is splitted in pretty good manner on the basis of dry so we don't have that much overhead in this.
