### ISSUE TITLE
remove `fetch()`

### ISSUE THREAD

**Issue by jasongitmail** [etherCorps/sveltekit-og#19]
I noticed in the built index.js that there are two fetches to external URLs.

```js
const fontFile = await fetch('https://sveltekit-og.ethercorps.io/noto-sans.ttf');
const fontData = await fontFile.arrayBuffer();
const indexWasmRes = await fetch('https://unpkg.com/svg2png-wasm/svg2png_wasm_bg.wasm');
const svg2PngWasmBuffer = await indexWasmRes.arrayBuffer();
```

It'd be preferable to use the NodeJS import approach in `svg2png-wasm` docs: https://github.com/ssssota/svg2png-wasm#nodejs--browser 

Is a default font necessary--does it look bad without one? Because if not required, maybe it's better to just exclude it. But if you think it's better to include it, it'd probably be better to include the font as part of `@ethercorps/sveltekit-og` and import it locally.

**Comment by theetherGit** [comment]
I'll look into it. Till then i'll leave as it is.
Main reason to use fetch was to avoid node modules error related to polyfills. If I can make it possible anyhow i'll look into it.

**Comment by baseplate-admin** [comment]
Maybe for fonts we can use [`@fontsource/noto-sans`](https://www.npmjs.com/package/@fontsource/noto-sans)

**Comment by theetherGit** [comment]
I'll try this on weekend but [@fontsource/noto-sans](https://www.npmjs.com/package/@fontsource/noto-sans) use `fs` and cloudflare doesn't have polyfills this. But if you have sometime then try to add it in `@ethercorps/sveltekit-og` and try it with `pnpm run test:build` to check if you get error then it's not possible.

**Comment by baseplate-admin** [comment]
Hi, is there any progress on this?
---
Regarding my findings : 
> I'll try this on weekend but [@fontsource/noto-sans](https://www.npmjs.com/package/@fontsource/noto-sans) use `fs`
Actually  [@fontsource/noto-sans](https://www.npmjs.com/package/@fontsource/noto-sans) is just a collection of `woff`s.
Check [npm](https://www.npmjs.com/package/@fontsource/noto-sans?activeTab=code)

**Comment by jasongitmail** [comment]
This is breaking my tests intermittently too because the fetch will fail intermittently

**Comment by theetherGit** [comment]
@jasongitmail can you provide the details like how it's breaking.

**Comment by theetherGit** [comment]
> Hi, is there any progress on this?
> 
> Regarding my findings :
> 
> > I'll try this on weekend but [@fontsource/noto-sans](https://www.npmjs.com/package/@fontsource/noto-sans) use `fs`
> 
> Actually [@fontsource/noto-sans](https://www.npmjs.com/package/@fontsource/noto-sans) is just a collection of `woff`s. Check [npm](https://www.npmjs.com/package/@fontsource/noto-sans?activeTab=code)

I understand that part but if we wants to remove fetch from library. I have to find a way which can work on `svg2png`. I don't want to introduce extra polyfills.

**Comment by jasongitmail** [comment]
Sure. While running my app's playwright tests with `npm runt test`, intermittently the tests timeout after 60 seconds and fail to start. The output includes this error, mentioning `sveltekit-og` and `fetch failed`: 

```sh
[WebServer] 
[WebServer] 
[WebServer] TypeError: fetch failed
    at fetch (/myapp/node_modules/undici/index.js:109:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async file:///myapp/node_modules/@ethercorps/sveltekit-og/index.js:7:22 {
  cause: Error [ERR_SOCKET_CONNECTION_TIMEOUT]: Socket connection timeout
      at new NodeError (node:internal/errors:399:5)
      at internalConnectMultiple (node:net:1099:20)
      at Timeout.internalConnectMultipleTimeout (node:net:1638:3)
      at listOnTimeout (node:internal/timers:575:11)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'ERR_SOCKET_CONNECTION_TIMEOUT'
  }
}
[WebServer] TypeError: fetch failed
```

Assuming you specify the same versions for the dependency when imported as a NodeJS dependency, it should be equally compatible with your current code. I've never encountered a scenario where an external dependency needed to be fetch'd over the network for a NodeJS package, but happy to talk it through if helpful.

**Comment by theetherGit** [comment]
@baseplate-admin as you mentioned to use [`@fontsource/noto-sans`](https://www.npmjs.com/package/@fontsource/noto-sans) but it's just a wrapper around the font files. Here we need font files so we can convert them to buffers. So we have to use `fs` which is not favorable because of `workerd (cloudflare's js runtime)`.

@jasongitmail i understand your issue i took a different approach but it have it's own side effects(worst to be accurate). You can check `remove fetch` branch. And i would love to know your alternative suggestions.

**Comment by theetherGit** [comment]
Providing polyfills is the issues because not every runtime have all polyfills. And managing the polyfill dependency is hard even confusing while deployment. I want it to be like install use no error because of dependencies & etc.

**Comment by theetherGit** [comment]
@DarthGigi Can you please share reproduction step or code example? As [this](https://sveltekit-og-vercel.vercel.app/) demo is hosted on vercel.

**Comment by DarthGigi** [comment]
> @DarthGigi Can you please share reproduction step or code example? As [this](https://sveltekit-og-vercel.vercel.app/) demo is hosted on vercel.

I’m unable to create a code example for 2 weeks since I’m on vacation. 

For the hosted vercel demo, is the runtime set to 'edge' (https://kit.svelte.dev/docs/adapter-vercel#deployment-configuration)?

**Comment by corysimmons** [comment]
@jasongitmail Did you ever find a solution to this?

**Comment by jasongitmail** [comment]
@corysimmons My hope is we can get a long term solution via [actual support in Satori or vercel/og](https://github.com/vercel/satori/issues/558). So we can worry less about a 3rd party package falling out of support. Maybe you could add a reaction there to support it please.

theetherGit also mentioned [workers-og](https://github.com/kvnang/workers-og) to me. It is Cloudflare specific and I'm not sure if it will work during development too, but I plan to try it out.  

He has [also mentioned he's working on his own approach](https://github.com/etherCorps/sveltekit-og/discussions/30) too, but I haven't seen any mention that it's ready for use yet.

**Comment by corysimmons** [comment]
@jasongitmail I spent all day on this, but I feel like I have a good approach now. 😮‍💨

I think you must have a SvelteKit API route for local development. This package (or just `satori-html` and `@vercel/og` and a few lines of code) will facilitate that.

If you want dynamic images in production, and you're using Cloudflare, you _need_ to use Cloudflare workers, and `workers-og` makes all the complicated WASM stuff pretty easy.

Try to share code between the two, and if you need to use any sort of assets from a file on the filesystem, you have to put it in `/static` and `fetch` it using the absolute URL for whichever env.

I'm going to sleep now, but assuming this strategy works, I might open-source a package for it tomorrow.

...Actually, now that I think about it, since you **have** to use Cloudflare workers _anyways_, you really don't even need this package, you only need `workers-og` and then just use `$ wrangler dev`.

Am I missing something? 🤔

**Comment by theetherGit** [comment]
I have to add multiple vite or rollup plugins but i'm trying first. This time i want to fix this completely but it's time taking when i have job side by side where i work on different things.
