### ISSUE TITLE
Add multi language font and Emoji support by default.

### ISSUE THREAD

**Issue by theetherGit** [etherCorps/sveltekit-og#2]
It's hard to do all thing manually when you have to add fonts or emoji’s by yourself when you are using a library to solve a problem. Sometimes you have different emoji's or different language text and by default we have to pass language support for that font. 

Loading assets by default would be a great thing, you can add support for multiple emoji api with a single font with multiple language support like (Noto sans).

A have considered how @vercel/og handle it but it's time consuming so we need a bit different approach for that. They made it with the approach of vercel edge network and in sveltekit-og we don't want that by default.

**Comment by theetherGit** [comment]
not able to do better

**Comment by Namaskar-1F64F** [comment]
Do emojis work? I can't figure out how to make them work. Using the Inter font and a different font. I followed what I thought to be exactly how next did it in an example, but it loads as a space with Inter and a box with the default font.

**Comment by theetherGit** [comment]
It works same as satori. 
https://github.com/vercel/satori/blob/7d8ee2b9d4ee097b2c04b19443bbae8e78cbef14/playground/pages/index.tsx#L119
That's how they are doing it in satori playground.
