### ISSUE TITLE
Example on how local fonts can be imported?

### ISSUE THREAD

**Issue by buhodev** [etherCorps/sveltekit-og#26]
**Is your feature request related to a problem? Please describe.**
Hi! Thanks for the work on this library. I'm struggling to find a way of using locally hosted fonts. Is this possible to do at the moment? Say I have `/static/fonts/inter-700.woff` in my project. How do I import the font file in the `+server.ts`? Is this possible to accomplish?

**Describe the solution you'd like**
Documentation on how to import font files from the `/static` folder if this is supported.

**Comment by buhodev** [comment]
Well, I ended up adapting the [example by Rich Geoff](https://github.com/geoffrich/sveltekit-satori/blob/f9bb379ae9bae69a34fe30d6dda129c50d29b005/src/routes/satori/%2Bserver.js#L10-L31) and it worked :)

**Comment by theetherGit** [comment]
Can you please update it the repo and test it in this?

**Comment by buhodev** [comment]
Are you referring to update the `etherCorps/sveltekit-og` repo?

**Comment by theetherGit** [comment]
Yes, You can contribute. You can try any method you see fit and we can discuss openly.

**Comment by buhodev** [comment]
Sure! Will do :)

**Comment by corysimmons** [comment]
>Say I have /static/fonts/inter-700.woff in my project. How do I import the font file in the +server.ts? Is this possible to accomplish?

@buhodev You just have to use absolute URLs like `http://localhost:5173/fonts/inter-700.woff` or `https://yoursite.com/fonts/inter-700.woff`

@theetherGit This can probably be closed.

**Comment by theetherGit** [comment]
Right now, i have taken same approach as `@vercel/og`.
