### ISSUE TITLE
Does not work on cloudflare pages

### ISSUE THREAD

**Issue by buhodev** [etherCorps/sveltekit-og#27]
**Describe the bug**
Everything works on local but doesn't work on cloudflare pages

**To Reproduce**

1. Clone https://github.com/buhodev/melt-ui-starter/
2. Deploy on cloudflare (e.g. [my-new-project].pages.dev)
3. Go to `[my-new-project].pages.dev/en/og`
4. See error 500 Internal error.

To see the logs on cloudflare dashboard:

1. Go to cloudflare dashboard 
2. Click on `Workers & Pages` on the left sidebar
  
![image](https://github.com/etherCorps/sveltekit-og/assets/105121122/94503ee2-b54c-41cf-81c8-7623884b6d97)

3. Click on `View details` on the bottom right of your project card
  
![image](https://github.com/etherCorps/sveltekit-og/assets/105121122/411497f0-ca6d-4f3c-b7b0-1ac7b30c9909)

4. Click on `Functions` tab and scroll down
5. Click on `Begin logs stream` button and wait until the Websocket connection is established.
  
![image](https://github.com/etherCorps/sveltekit-og/assets/105121122/8695447f-cf4c-4057-8764-d946b9ec2f2a)

7. Go to `[my-new-project].pages.dev/en/og` again to trigger the function.
8. Click on the last GET log
  
![image](https://github.com/etherCorps/sveltekit-og/assets/105121122/5e949233-1ccf-4df8-b33d-3a7f62c11df5)

10. See the error trace:
```json
{
  "outcome": "ok",
  "scriptName": "pages-worker--1264517-production",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [
    {
      "message": [
        "CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder"
      ],
      "level": "log",
      "timestamp": 1690291911201
    },
    {
      "message": [
        "Error: WASM has not been initialized. Call `initialize` function."
      ],
      "level": "error",
      "timestamp": 1690291911201
    }
  ],
  ...
}
```

**Expected behavior**
The `/og` route should generate the image

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome

**Additional context**

**Comment by theetherGit** [comment]
ok got the i'll test on your deployment

**Comment by buhodev** [comment]
Thanks. Let me know if you need anything from my end

**Comment by theetherGit** [comment]
Sure. I found the issue but i have to look what i can do. As of now it looks like #19 may be the reason. As cf has limited cpu time for every request. I have to go more deep for that.

**Comment by corysimmons** [comment]
Was this ever fixed or does `sveltekit-og` still not work on Cloudflare Pages? 😟

**Comment by theetherGit** [comment]
Still trying to get it work on workers.

**Comment by theetherGit** [comment]
It's not going to work on cloudflare workers. I have tried so many times, I'm unable to make it work on edge runtime.

**Comment by buhodev** [comment]
Thanks @theetherGit. I tried also to make it work with `@resvg/resvg-js` + `satori` + `satori-html` but  only at build time (not useful since it's not dynamic).

**Comment by corysimmons** [comment]
I got it working in CF Workers with just `satori-html` and `workers-og`.

```ts
import { Response as TResponse, Request } from "@cloudflare/workers-types";
import { ImageResponse } from "workers-og";
import { html as satoriHtml } from "satori-html";

// React stuff
import * as React from "react";
import { renderToString } from "react-dom/server";

export default {
  async fetch(request: Request, env: Env): Promise<TResponse> {
    // const html = I generate HTML from a React component + React.renderToString

    const imageResponse = new ImageResponse(
      satoriHtml(html) as React.ReactNode,
      {
        width: 1200,
        height: 630,
        fonts: [{ name: "TT Hoves Pro", data: fontData, weight: 600 }],
      }
    );

    // Put the file in a CF bucket and respond with a URL.
  },
};
```

**Comment by theetherGit** [comment]
You are making a direct use of `workers-og`. Please try to use with sveltekit and then build it.

Between you can use `@ethercorps/svelte-h2j` which can convert svelte to jsx, it can be used standalone but you will need `svelte` as dependency.
