### ISSUE TITLE
Error in ImageResponse

### ISSUE THREAD

**Issue by ak4zh** [etherCorps/sveltekit-og#3]
**Describe the bug**
Error: The "source" argument must be an instance of Response or an Promise resolving to Response. Received an instance of Response

Results in error as soon as I import `import { ImageResponse } from '@ethercorps/sveltekit-og';`

**Comment by theetherGit** [comment]
Is it a typescript issue??

**Comment by ak4zh** [comment]
@theetherGit As soon as I run the app and visit the og endpoint and it crash.

```bash
[APP] /Users/ak4zh/CodeProjects/swyxkit/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
[APP]         throw ex;
[APP]         ^
[APP] 
[APP] TypeError [ERR_INVALID_ARG_TYPE]: The "source" argument must be an instance of Response or an Promise resolving to Response. Received an instance of Response
[APP]     at new NodeError (node:internal/errors:393:5)
[APP]     at node:internal/wasm_web_api:24:13
[APP]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[APP]   code: 'ERR_INVALID_ARG_TYPE'
[APP] }
[APP] 
[APP] Node.js v18.9.1
[APP] npm run dev exited with code 7

```

**Comment by theetherGit** [comment]
I haven't encountered with this problem when i tried to setup swyxkit if possible please push your code and i'll test it. 
I have added examples dir in this project you can test it there too.

**Comment by theetherGit** [comment]
@ak4zh waiting for response

**Comment by darianrosebrook** [comment]
Same issue here it seems with
 ```
pseudo-path.../node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

[LinkError: WebAssembly.instantiate(): Import #0 module="wbg" function="__wbg_new_651776e932b7e9c7" error: function import requires a callable]
 ELIFECYCLE  Command failed with exit code 7.
```

and this is using your example code, with sveltekit's release of 1.0.0-next.563

**Comment by theetherGit** [comment]
I got it i'm working on it. I have decided to rewrite it from scratch because of some problem related to wasm and planning to use svelte compiler to generate react like object. Please wait for some time.

**Comment by darianrosebrook** [comment]
Thanks for looking into it! Cheers (:

**Comment by theetherGit** [comment]
Everything is perfectly working with all the new changes
