### ISSUE TITLE
README is incorrect, stating it needs to be installed as dev dependency.

### ISSUE THREAD

**Issue by rbozan** [etherCorps/sveltekit-og#31]
**Describe the bug**
It states you need to install this package as DEV dependency, but according to the following this won't work:

https://kit.svelte.dev/docs/adapter-node#deploying

> Development dependencies will be bundled into your app using Rollup. To control whether a given package is bundled or externalised, place it in devDependencies or dependencies respectively in your package.json.

In my case, using `npm preview` works, but using the built package with `node build` won't work and results in a 500 error.

Using it as a normal dependency works.

**Comment by theetherGit** [comment]
ok Got it if you like to update the readme for node please do that.

**Comment by theetherGit** [comment]
Done
