### ISSUE TITLE
commit 501efa9 overwrote the README

### ISSUE THREAD

**Issue by MihkelMK** [etherCorps/sveltekit-og#34]
On commit 501efa9, the README was overwritten with the default README for create-svelte. Was this intentional?

**Comment by theetherGit** [comment]
It was done by mistake. But i left it as it is because i'm trying to make it work on cloudflare, vercel and vercel edge. It's not easy for me to make it possible.

**Comment by MihkelMK** [comment]
Wouldn't it be better to restore it on the mean time? I'm currently using it with a node server and wanted to look at the current documentation. Maybe add a disclaimer at the top that expresses your current focus? I can make a PR if you don't have the time right now.

**Comment by theetherGit** [comment]
if you can add please do this.

**Comment by theetherGit** [comment]
Done
