### ISSUE TITLE
text field not working

### ISSUE THREAD

**Issue by jdgamble555** [etherCorps/sveltekit-og#37]
As soon as I add a `text` field in an svg, I get `ERR_EMPTY_RESPONSE`.  I remove it from the svg, all works:

```ts
<text x="65" y="55">Grumpy!</text>
```

This is on my local machine, which obviously has fonts installed.

J

**Comment by theetherGit** [comment]
Which version?

**Comment by jdgamble555** [comment]
You can close this. It seems `@vercel/og` does not support text fields itself.
