### ISSUE TITLE
`new ImageResponse` or `async ImageResponse`?

### ISSUE THREAD

**Issue by rbozan** [etherCorps/sveltekit-og#43]
When I return `ImageResponse` without `new` after upgrading, it seems I get the following error:

```
TypeError: Class constructor ImageResponse cannot be invoked without 'new'
    at GET (/home/rbozan/Projects/learning/game/src/routes/og_course/[id]/+server.ts:57:38)

```

However changing it from

```
	return await ImageResponse(
```

to 
```
  return new ImageResponse(
```

(replace `await` with `new`) fixes it.

The README.md does not construct a new instance of ImageResponse. So, is it needed or not?

**Comment by theetherGit** [comment]
use with new, documentation error.
